name: sem-hf-stream
channels:
  - conda-forge
  - pytorch
dependencies:
  - accelerate
  - cpuonly
  - datasets
  - evaluate
  - ipykernel
  - ipywidgets
  - pip
  - protobuf
  - pytorch
  - scikit-learn
  - scipy
  - sentencepiece
  - streamlit
  - torchaudio
  - torchvision
  - pip
  - pip:
      - spacy
      - streamlit-agraph
      - -e ../transformers
