name: sem
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - accelerate
  - datasets
  - evaluate
  - ipykernel
  - ipywidgets
  # - ninja
  # - packaging
  - protobuf
  - pynvml
  - pytorch
  - pytorch-cuda>=12.1
  - scikit-learn
  - scipy
  - sentencepiece
  - torchaudio
  - torchvision
  - pip
  - pip:
      # - spacy
      # - flash-attn --no-build-isolation
      - git+https://github.com/philheller/transformers.git
      # - -e ../transformers
