name: sem
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - accelerate
  - datasets
  - evaluate
  - ipykernel
  - ipywidgets
  - protobuf
  - pytorch
  - pytorch-cuda>=12.1
  - scikit-learn
  - scipy
  - sentencepiece
  - spacy
  - torchaudio
  - torchvision
  - pip
  - pip:
      - git+https://github.com/philheller/transformers.git
      # - -e ../transformers
